name: Create PR

on:
  workflow_dispatch:

jobs:
  create:
    runs-on: ubuntu-latest

    steps:

      - name: Prepare Git Repository
        uses: actions/checkout@v2

      - name: Create PR
        run: gh pr create -B custom/cat -H mastodon:main -t "Scheduled update from upstream" -b "Created by GitHub Actions" --no-maintainer-edit
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
