name: Create PR

on:
  workflow_dispatch:

jobs:
  create:
    runs-on: ubuntu-latest

    steps:

      - name: Create PR
        run: gh pr create -R ${{ github.repository }} -B custom/cat -H mastodon:main -t "Scheduled update from upstream" -b "Created by GitHub Actions"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
