name: Create PR

on:
  workflow_dispatch:

jobs:
  create:
    runs-on: ubuntu-latest

    steps:

      - name: Prepare Git Repository
        uses: actions/checkout@v2

      - name: Create PR
        run: hub pull-request -b custom/cat -h mastodon:main -m "Scheduled update from upstream" -m "Created by GitHub Actions"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
